keys:
  - &higgs age1zwsq6rx0ur4nd6lrfnrhqf6afxrnwffzcdwpkrtylgy8smm5mgssymd9hk
  - &photon age10jhs53hk0t2g8k4xsa7fsunpzeeuhqlfdcpzg9m6x2dgn8nam95sp8wr0v
creation_rules:
  - path_regex: global/secrets.yaml$
    key_groups:
      - age:
          - *higgs
          - *photon
  - path_regex: hosts/.*/secrets.yaml$
    key_groups:
      - age:
          - *higgs
          - *photon
