{
  pkgs,
  lib,
  config,
  ...
}:
{
  imports = [ ./hardware-configuration.nix ];

  sops.secrets."homarr.env".sopsFile = ./secrets.yaml;

  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."homarr" = {
    image = "ghcr.io/homarr-labs/homarr:latest";
    environmentFiles = [
      config.sops.secrets."homarr.env".path
    ];
    volumes = [
      "/var/run/podman/podman.sock:/var/run/podman/podman.sock:rw"
    ];
    ports = [
      "7575:7575/tcp"
    ];
    labels = {
      "compose2nix.settings.sops.secrets" = "homarr.env";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=homarr"
      "--network=homarr_default"
    ];
  };
  systemd.services."podman-homarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-homarr_default.service"
    ];
    requires = [
      "podman-network-homarr_default.service"
    ];
    partOf = [
      "podman-compose-homarr-root.target"
    ];
    wantedBy = [
      "podman-compose-homarr-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-homarr_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f homarr_default";
    };
    script = ''
      podman network inspect homarr_default || podman network create homarr_default
    '';
    partOf = [ "podman-compose-homarr-root.target" ];
    wantedBy = [ "podman-compose-homarr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-homarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };

  services.caddy = {
    enable = true;
    virtualHosts.":80".extraConfig = "reverse_proxy :7575";
  };

  networking.firewall.allowedTCPPorts = [
    7575
    80
  ];
}
